### ISSUE TITLE
Register one model for all symbols

### ISSUE THREAD

**Issue by SiBensberg** [edtechre/pybroker#10]
Hi,
I am trying to register one model for backtesting all symbols. Is there an intended way to do that?
If I understood the documentation right, while backtesting a symbol the respective model gets loaded. How to load a "general" model?

`https://www.pybroker.com/en/latest/notebooks/6.%20Training%20a%20Model.html`

Best regards

**Comment by edtechre** [comment]
Hi @SiBensberg,

Training a model using multiple symbols is not currently supported. However, you can use the ``pretrained`` option to load a custom model that has been trained on multiple symbols:
https://www.pybroker.com/en/latest/reference/pybroker.model.html#pybroker.model.model
