### ISSUE TITLE
Multi-timeframe?

### ISSUE THREAD

**Issue by tsunamilx** [edtechre/pybroker#101]
A simple example: I need 2 indicators, one from daily time frame, another from weekly time frame, when the daily one is above the weekly one, enter long position, when the daily one is below the weekly one, exit long position.

Is it possible? Any suggestions? 

Thanks.

**Comment by edtechre** [comment]
Hi @tsunamilx,

I would suggest creating an indicator that repeats the weekly value for every day of the week. You could also do this by adding a column to your data frame that does the weekly calculation and [registering it with PyBroker](https://www.pybroker.com/en/latest/notebooks/7.%20Creating%20a%20Custom%20Data%20Source.html#Using-a-Pandas-DataFrame).

In either case you would then execute a strategy on daily data, and perform the check between your weekly indicator/column and daily indicator.

**Comment by tsunamilx** [comment]
Thanks, this is actually what I started to do.
