### ISSUE TITLE
Add regular defined contribution to portfolio

### ISSUE THREAD

**Issue by Djangu-algo** [edtechre/pybroker#104]
Feature request please:
If possible, a portfolio could have a regular cash contribution amount, or an amount from a list / dataframe, so that it can mimic a retirement plan. Conversely, a withdrawal amount could also be entered as a negative amount.

**Comment by edtechre** [comment]
Hi @Djangu-algo, 

I'm not sure how this would work. What would the amount be from the list or data frame, and how would these be updated? You can configure your own cash amount to use for your strategy.
