### ISSUE TITLE
Add Ruff for Python linter and code formatter

### ISSUE THREAD

**Issue by albertandking** [edtechre/pybroker#106]
Hi, Ed
1. Ruff is An extremely fast Python linter and code formatter, written in Rust. refer: https://docs.astral.sh/ruff/
2. We can consider use ruff as linter and code formatter
3. I can make some changes to dev branch

**Comment by edtechre** [comment]
Thank you Albert! This sounds good to me, I will take a look.

**Comment by edtechre** [comment]
Hi Albert, this looks good. Happy to review changes once they make it to the dev branch.

**Comment by albertandking** [comment]
> Hi Albert, this looks good. Happy to review changes once they make it to the dev branch.

Hi, Ed, can you rerun the actions and test it?
