### ISSUE TITLE
Real-time question

### ISSUE THREAD

**Issue by guiramos** [edtechre/pybroker#115]
Ok, maybe I didn't understand the purpose of the project correctly, but is there a way to use it make decisions in real-time, like using newly closed candles?

The only examples I Saw were about backtesting. And they are perfect for validating a strategy, but how can I use it in a way, and that, I got this new candle, apply whatever rules, let me call the brokerage api and actually perform the operation (buy or sell)?

How? Can you provide examples?

**Comment by edtechre** [comment]
Hello @guiramos,

Currently, PyBroker is only intended for backtesting. But I plan to introduce a module that could support live trading with a brokerage API in the future.
