### ISSUE TITLE
Not installable on Python 3.11.2

### ISSUE THREAD

**Issue by RandomBloke85** [edtechre/pybroker#12]
Hello

Thank you for developping this fantastic library. I'd love to use it, but running Python 3.11.2. Will it be available for that version in the near future?

However, this seems to be an issue with numba:

```
Collecting numba<1,>=0.56.3 (from lib-pybroker)
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\center\AppData\Local\Temp\pip-install-36wtc8qn\numba_4157527a6be444afb3ba3015b4b34b93\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\center\AppData\Local\Temp\pip-install-36wtc8qn\numba_4157527a6be444afb3ba3015b4b34b93\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Thank you

**Comment by jindaxiang** [comment]
> Hello
> 
> Thank you for developping this fantastic library. I'd love to use it, but running Python 3.11.2. Will it be available for that version in the near future?
> 
> However, this seems to be an issue with numba:
> 
> ```
> Collecting numba<1,>=0.56.3 (from lib-pybroker)
>   Using cached numba-0.56.4.tar.gz (2.4 MB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\center\AppData\Local\Temp\pip-install-36wtc8qn\numba_4157527a6be444afb3ba3015b4b34b93\setup.py", line 51, in <module>
>           _guard_py_ver()
>         File "C:\Users\center\AppData\Local\Temp\pip-install-36wtc8qn\numba_4157527a6be444afb3ba3015b4b34b93\setup.py", line 48, in _guard_py_ver
>           raise RuntimeError(msg.format(cur_py, min_py, max_py))
>       RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```
> 
> Thank you

Hello, 
1. It seems that you can remove jit functions from the source code
2. Then install numpy from source code

**Comment by edtechre** [comment]
Hi @RandomBloke85,

This is because PyBroker depends on Numba, and Numba does not yet support Python 3.11. However, Numba support is coming very soon, and there is a release candidate available for 3.11 (https://github.com/numba/numba/issues/8841). In the meantime, you will need to use Python 3.9 or 3.10.

**Comment by edtechre** [comment]
Hi @RandomBloke85,

Good news! PyBroker v1.1.9 now supports Python 3.11.

**Comment by RandomBloke85** [comment]
Hi @edtechre 

Thanks for letting me know. Just installed without flaws so far. Will have a look into it. Thx for developping such a great tool!

**Comment by edtechre** [comment]
Thanks @RandomBloke85!

I just pushed a change today that affects how market values of short positions are calculated. Be sure to upgrade to the latest version:
pip install --upgrade lib-pybroker
