### ISSUE TITLE
how to realize multi time frame backtest?

### ISSUE THREAD

**Issue by shiniantianlang** [edtechre/pybroker#13]
Can pybroker realize the multi time frame backtest? For example, for 5 minutes data transaction, the signal uses 10 minutes of data.

**Comment by edtechre** [comment]
Hi @shiniantianlang,

Yes, but you need to perform this manually. For instance, you can create an indicator using 5-minute bars and manually compute the indicator values using 10 minutes of data, which would involve using 2 five-minute bars.

**Comment by shiniantianlang** [comment]
Thank you very much for your answer, I will try this method.
