### ISSUE TITLE
Can ctx.score work with ctx.sell_shares?

### ISSUE THREAD

**Issue by none2003** [edtechre/pybroker#131]
Hi @edtechre,

In example of [Rotational Trading](https://www.pybroker.com/en/latest/notebooks/10.%20Rotational%20Trading.html), ctx.score was used to pair with ctx.buy_shares, can it work with ctx.sell_shares? 

As a counterexample, how to achieve: "We _**cover**_ the currently held stock short position if it is no longer ranked among the _**bottom**_ five 20-day ROCs. Otherwise, we rank all stocks by their 20-day ROC and _**sell the bottom two ranked**_. "

**Comment by edtechre** [comment]
Yes, just make sure to set [max_short_positions](https://www.pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.max_short_positions).
