### ISSUE TITLE
when use  stop loss,  how to get callback while trigger stop action

### ISSUE THREAD

**Issue by zhuzw1987** [edtechre/pybroker#136]
Hi, Ed
when use  stop loss,  how to get callback while trigger stop action?

**Comment by edtechre** [comment]
Hi @zhuzw1987, there is no callback that is triggered when a stop is executed. You can however check whether the last trade that was placed was due to a stop by using [Context#trades](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.BaseContext.trades)
