### ISSUE TITLE
AlpacaCrypto Object is not callable

### ISSUE THREAD

**Issue by rgonzales98** [edtechre/pybroker#137]
I've been trying to pull crypto data from alpace using their sandbox/paper api. It word for regular stocks but not for crypto for some reason.

`from pybroker import Strategy, YFinance, highest, AlpacaCrypto

def exec_fn(ctx):
    # Get the rolling 10 day high.
    high_10d = ctx.indicator('high_10d')
    # Buy on a new 10 day high.
    if not ctx.long_pos() and high_10d[-1] > high_10d[-2]:
        ctx.buy_shares = 100
        # Hold the position for 5 days.
        ctx.hold_bars = 5
        # Set a stop loss of 2%.
        ctx.stop_loss_pct = 2

crypto = AlpacaCrypto(api_key="I_replaced_with_key", api_secret="I_replaced_with_secret")
strategy = Strategy(crypto(), start_date='1/1/2023', end_date='7/1/2024')
strategy.add_execution(
    exec_fn, ['USD/BTC'], indicators=highest('high_10d', 'close', period=10))
# Run the backtest after 20 days have passed.
result = strategy.backtest(warmup=20)`

`Traceback (most recent call last):
  File "/home/pybot/run.py", line 15, in <module>
    strategy = Strategy(crypto(), start_date='1/1/2022', end_date='7/1/2022')
                        ^^^^^^^^
TypeError: 'AlpacaCrypto' object is not callable
`

**Comment by edtechre** [comment]
Hi @rgonzales98,

This is because the ``crypto`` variable is not Callable.
