### ISSUE TITLE
set stop order without buy_shares or sell_shares; how to set partial stop loss?

### ISSUE THREAD

**Issue by xiadingZ** [edtechre/pybroker#155]
**Question 1:**

How to set stop order alone, without but_shares or sell_shares?

This is my code. I want to set a new stop order when some conditions are meet, but it throws error
```
  if ctx.close[-1] > ctx.indicator('kc_up')[-1] and ctx.close[-2] > ctx.indicator('kc_up')[-2]:
      ctx.cancel_stops(ctx.symbol) # cancel previous stop_loss if exists
      ctx.stop_trailing_limit = ctx.indicator('kc_up')[-1]  # set new stop loss to previous keltern channel's up band
      return   
```

```
ValueError: Either buy_shares or sell_shares must be set when a stop is set.
```

**Question 2:**

How to set partial stop loss. eg: exists my 50% positions.

**Comment by edtechre** [comment]
Hi @xiadingZ,

You need to specify ctx.buy_shares or ctx.sell_shares when setting the stop with:
`ctx.stop_trailing_limit = ctx.indicator('kc_up')[-1]`

The stop is then associated with the position opened with the number of buy_shares/sell_shares.

For #2, partial stop loss is not supported. You can instead exit 50% of your position by matching some condition and setting ctx.sell_shares accordingly. Also see [calc_target_shares](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.BaseContext.calc_target_shares).

**Comment by xiadingZ** [comment]
Hi, @edtechre 

1. Do you mean `stop_trailing_limit ` will be updated to `ctx.indicator('kc_up')[-1]` at each new bar? 
2. If I want to set stop loss as follows first, then at first time `ctx.close[-1] > ctx.indicator('kc_up')[-1] and ctx.close[-2] > ctx.indicator('kc_up')[-2]`, I add a new `stop_trailing_limit ` set as `ctx.indicator('kc_up')[-1]` ,  how to do it?
```
                    ctx.buy_shares = ctx.calc_target_shares(0.25)
                    ctx.buy_limit_price = ctx.close[-1] + 0.05
                    ctx.stop_loss_pct = 20
                    ctx.stop_loss_limit = min(ctx.close[-5:]) - 0.1
                    ctx.hold_bars = 40
```

**Comment by edtechre** [comment]
Hi @xiadingZ 

> Do you mean stop_trailing_limit  will be updated to ctx.indicator('kc_up')[-1] at each new bar?

No, the stop_trailing_limit sets the limit price for the trailing stop. It is only set once.

> If I want to set stop loss as follows first, then at first time ctx.close[-1] > ctx.indicator('kc_up')[-1] and ctx.close[-2] > ctx.indicator('kc_up')[-2], I add a new stop_trailing_limit  set as ctx.indicator('kc_up')[-1] , how to do it?

You can cancel a stop, see https://www.pybroker.com/en/latest/notebooks/8.%20Applying%20Stops.html#Canceling-a-Stop.

**Comment by xiadingZ** [comment]
I'm confused with `stop_trailing_pct` and `stop_trailing_limit `. hers is my code
```
            ctx.buy_shares = ctx.calc_target_shares(0.1)
            ctx.buy_limit_price = ctx.close[-1] + 0.05
            ctx.stop_trailing_pct = 20
            ctx.stop_trailing_limit = min(ctx.low[-5:]) - 0.1
```

> A trailing stop is an order that is used to exit a trade once the instrument’s price falls a certain percentage or cash amount below its highest market price

Here is my understandation:
1. At bar 0, I set ctx.stop_trailing_pct = 20.  Market Price is MP0, then when market price touchs MP0 * 80% at future bar, my stop order is excuted.
2. At bar 1, market price is MP1. If MP1 < MP0, the when market price touchs MP0 * 80% at future bar, my stop order is excuted
3. At bar 2, market price is MP2. If MP2 > MP0, the when market price touchs MP2 * 80% at future bar, my stop order is excuted.

1. Is this correct? 
2. What's the usage of stop_trailing_limit?  Is when market price touch `max(MP2 * 80%, stop_trailing_limit)` then excute stop order?
3. If stop_trailing_limit is not updated at each new bar, what's the difference of `stop_trailing_limit` and `stop_loss_limit `

**Comment by edtechre** [comment]
Hi @xiadingZ,

Stops are executed on the same bar that the condition was hit.

For 2), stop_trailing_limit simply sets the limit price to use for the stop order. If the limit price is not met, then the stop is not triggered.

For 3), ```stop_trailing_limit``` sets the limit price for the trailing stop set with ```stop_trailing*```.  ```stop_loss_limit``` sets the limit price for the stop set with ```stop_loss*```.
