### ISSUE TITLE
Better plotting

### ISSUE THREAD

**Issue by none2003** [edtechre/pybroker#22]
Hi edtechre,

I've been using backtesting.py for a while now and I think one of its nice features is its mapping feature, which automatically opens the browser after each backtesting and shows an interactive chart, so it's easy to see where the current strategy needs further optimization.  You can see such interactive charts on their website (https://kernc.github.io/backtesting.py), is pybroker planning to make such charts as well?

**Comment by edtechre** [comment]
Yes, visualizations is something I would like to add. In the meantime, have you tried using the [quantstats](https://github.com/ranaroussi/quantstats) package?

**Comment by none2003** [comment]
I used quantstats with backtrader before, it was nice, but it's not interactive like backtesting.py did, I think backtesting.py is using bokeh at the backend.
