### ISSUE TITLE
Pip error when installing lib-pybroker

### ISSUE THREAD

**Issue by luigibrancati** [edtechre/pybroker#3]
I tried installing `lib-pybroker` in a `conda` environment with Python 3.10 and I'm getting an error:
```
$ conda create -n test_pyb python==3.10
$ conda activate test_pyb
$ pip install -U pip setuptools wheel
$ pip install lib-pybroker
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbconvert 7.2.9 requires jinja2>=3.0, which is not installed.
nbconvert 7.2.9 requires markupsafe>=2.0, which is not installed.
nbclassic 0.5.1 requires jinja2, which is not installed.
jupyter-server 2.1.0 requires jinja2, which is not installed.
jupyter-events 0.6.3 requires jsonschema[format-nongpl]>=3.2.0, which is not installed.
```
Here's my pip freeze
```
aiohttp==3.8.1
aiosignal==1.3.1
alpaca-trade-api==2.3.0
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi==1.15.1
charset-normalizer==2.1.1
comm==0.1.2
cryptography==39.0.2
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
deprecation==2.1.0
diskcache==5.4.0
docker==6.0.1
dockerpty==0.4.1
docopt==0.6.2
executing==1.2.0
fastjsonschema==2.16.2
frozendict==2.3.5
frozenlist==1.3.3
html5lib==1.1
idna==3.4
ipykernel==6.20.2
ipython==8.9.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
jedi==0.18.2
joblib==1.2.0
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-events==0.6.3
jupyter_client==8.0.1
jupyter_core==5.1.5
jupyter_server==2.1.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
lib-pybroker==1.0.17
llvmlite==0.39.1
lxml==4.9.2
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack==1.0.3
multidict==6.0.4
multitasking==0.0.11
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numba==0.56.4
numpy==1.23.5
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
platformdirs==2.6.2
progressbar2==4.2.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
Pygments==2.14.0
pyrsistent==0.19.3
python-dateutil==2.8.2
python-dotenv==0.21.1
python-json-logger==2.0.4
python-utils==3.5.2
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4
stack-data==0.6.2
terminado==0.17.1
texttable==1.6.7
tinycss2==1.2.1
tornado==6.2
traitlets==5.8.1
urllib3==1.26.14
wcwidth==0.2.6
webencodings==0.5.1
websocket-client==1.5.1
websockets==10.4
widgetsnbextension==4.0.5
yarl==1.8.2
yfinance==0.2.12
```

This is non blocking,  manually installing `jinja2` solves the issue. Also, for some reason it seems this happens only on `conda` environments.

**Comment by edtechre** [comment]
Thank you for reporting!

Can you post your version of conda and your platform? I tried on conda==23.1.0 on Linux and conda==4.12 on Windows and I could not repro. 

Also there should not be any (transitive) dependency on nbconvert or jupyter in the dependency graph (unless you are installing requirements.txt from the Git repo). These are the dependencies in setup.cfg:

alpaca-trade-api>=2.3.0,<3
diskcache>=5.4.0,<6
joblib>=1.2.0,<2
numba>=0.56.3,<1
numpy>=1.23.4,<2
pandas>=1.5.1,<2
progressbar2>=4.1.1,<5
yfinance>=0.1.84,<1


And here is what my pip freeze looks like:

aiohttp==3.8.1
aiosignal==1.3.1
alpaca-trade-api==2.3.0
appdirs==1.4.4
async-timeout==4.0.2
attrs==22.2.0
beautifulsoup4==4.11.2
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==39.0.2
deprecation==2.1.0
diskcache==5.4.0
frozendict==2.3.5
frozenlist==1.3.3
html5lib==1.1
idna==3.4
joblib==1.2.0
lib-pybroker==1.0.17
llvmlite==0.39.1
lxml==4.9.2
msgpack==1.0.3
multidict==6.0.4
multitasking==0.0.11
numba==0.56.4
numpy==1.23.5
packaging==23.0
pandas==1.5.3
progressbar2==4.2.0
pycparser==2.21
python-dateutil==2.8.2
python-utils==3.5.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
six==1.16.0
soupsieve==2.4
urllib3==1.26.14
webencodings==0.5.1
websocket-client==1.5.1
websockets==10.4
yarl==1.8.2
yfinance==0.2.12

**Comment by edtechre** [comment]
Since many dependencies you list from `pip freeze` are not found in PyBroker's dependency graph, and because this only happens when you install via conda, I suspect this may be specific to your conda setup. I could not repro myself, so I am closing this. I will reopen if anyone else reports a similar issue.
