### ISSUE TITLE
How to use indicator with multiple outputs?

### ISSUE THREAD

**Issue by none2003** [edtechre/pybroker#30]
Hi @edtechre,

Since pyb support talib indicators, I tried Bollinger Bands like:

```
bb = pybroker.indicator('bb', lambda data: talib.BBANDS(data.close))
bb(df)
```

I got this error:

> ValueError: Length of values (3) does not match length of index (505)

I think the reason is BBANDS return 3 outputs.

```
help(talib.BBANDS)
Help on function BBANDS in module talib._ta_lib:
BBANDS(...)
    BBANDS(real[, timeperiod=?, nbdevup=?, nbdevdn=?, matype=?])
    
    Bollinger Bands (Overlap Studies)
    
    Inputs:
        real: (any ndarray)
    Parameters:
        timeperiod: 5
        nbdevup: 2
        nbdevdn: 2
        matype: 0 (Simple Moving Average)
    Outputs:
        upperband
        middleband
        lowerband
```

**Comment by none2003** [comment]
Hi @edtechre,

I have used backtesting.py, which also uses a decorator to encapsulate the results returned by the indicator:

```
self.upperband, self.middleband, self.lowerband = self.I(talib.BBANDS, self.data.Close)
```

These return values can then be used in the "next" method (similar to the "execute(ctx: ExecContext)" method in pyb):

```
...
if self.data.Close[-1] > self.upperband[-1]:
    pass
...
```

This is much easier than defining a method for each return value of the indicator, and I really hope pyb supports such a feature.



Maybe you can take a look at their implementation of this "I" method:

https://github.com/kernc/backtesting.py/blob/master/backtesting/backtesting.py  line 78

**Comment by edtechre** [comment]
Hi @none2003,

I may be able to add support for this by allowing multiple indicator names:

pybroker.indicator(name=['upperband', 'middleband', 'lowerband'], lambda data: talib.BBANDS(data.close))

I will look into the feasibility of this.

**Comment by none2003** [comment]
> Hi @none2003,
> 
> I may be able to add support for this by allowing multiple indicator names: ` pybroker.indicator(name=['upperband', 'middleband', 'lowerband'], lambda data: talib.BBANDS(data.close))`
> 
> I will look into the feasibility of this.

Hi @edtechre,

This looks good, have you had time to research on this?

**Comment by tsunamilx** [comment]
Hi @edtechre 

So what you suggest is like:
```python
bbup = pybroker.indicator('bbup', lambda data: talib.BBANDS(data.close).upperband)
bbdn = pybroker.indicator('bbdn', lambda data: talib.BBANDS(data.close).lowerband)
bbmd = pybroker.indicator('bbmd', lambda data: talib.BBANDS(data.close).middleband)
```
Is that right? If so, will it repeat the bbands calculation 3 times?

**Comment by edtechre** [comment]
Hi @tsunamilx,

Yes, that is true. But the TA-Lib calculation is very fast, so you should see very little difference in performance.
