### ISSUE TITLE
How to use it for live trading if I have a write a strategy using this package?

### ISSUE THREAD

**Issue by ruifeng96150** [edtechre/pybroker#32]

**Comment by edtechre** [comment]
Hi @ruifeng96150,

PyBroker does not currently support live trading. However, you can utilize the models trained with PyBroker in a live strategy.

**Comment by webbt127** [comment]
Is there a way to extract the trained model object from a backtest?

**Comment by edtechre** [comment]
You can save your trained model inside of the train function.

**Comment by webbt127** [comment]
Can't believe I didn't think of that. Thanks!
