### ISSUE TITLE
"Native library not available" error

### ISSUE THREAD

**Issue by robustness-data** [edtechre/pybroker#36]
Hi there! I tried to run a sample code and got this error: "RuntimeError: Native library not available at ... /Users/usr/opt/anaconda3/envs/pybroker39/lib/python3.9/site-packages/py_mini_racer/libmini_racer.dylib

Anyone had the same issue before?

**Comment by edtechre** [comment]
Which notebook do you see this on?

It looks like libmini_racer is required by AKShare. If you don't plan to use AKShare, then it shouldn't cause a problem.

**Comment by albertandking** [comment]
> Hi there! I tried to run a sample code and got this error: "RuntimeError: Native library not available at ... /Users/usr/opt/anaconda3/envs/pybroker39/lib/python3.9/site-packages/py_mini_racer/libmini_racer.dylib
> 
> 
> 
> Anyone had the same issue before?

Hi
If you are macOS users it may appear! 
I will add some docs for it!

**Comment by albertandking** [comment]
> Which notebook do you see this on?
> 
> 
> 
> It looks like libmini_racer is required by AKShare. If you don't plan to use AKShare, then it shouldn't cause a problem.

It's a error for macos，I will write a PR for this!

**Comment by edtechre** [comment]
Hi @albertandking,

Was https://github.com/edtechre/pybroker/pull/42 the fix for this issue?

**Comment by robustness-data** [comment]
@edtechre @albertandking Thank you all for response! I do use MAC OS system to run the sample notebook, and tend to use AKshare. If you could propose a solution that would be really helpful for MAC users. Thanks!

**Comment by edtechre** [comment]
@robustness-data Can you update PyBroker and try again? This may have been fixed with https://github.com/edtechre/pybroker/pull/42

**Comment by vikasgola** [comment]
@edtechre Not fixed. same issue.

**Comment by edtechre** [comment]
@vikasgola This only affects the usage of the AKShare DataSource, correct?

**Comment by edtechre** [comment]
@vikasgola I updated PyBroker to move the AKShare DataSource to a separate module. This should now no longer be an issue unless you explicitly import AKShare.

**Comment by edtechre** [comment]
If you still need to use AKShare, [see this issue for details on how to resolve](https://github.com/sqreen/PyMiniRacer/issues/143).

**Comment by albertandking** [comment]
> @edtechre @albertandking Thank you all for response! I do use MAC OS system to run the sample notebook, and tend to use AKshare. If you could propose a solution that would be really helpful for MAC users. Thanks!

I apologize for the late response. The official documentation of Akshare has a tutorial on configuring the M-series processors, but it is in Chinese; here, I will briefly introduce how to set it up.
1. download the lib here: https://jfds-1252952517.cos.ap-chengdu.myqcloud.com/akshare/software/pyminiracer/libmini_racer.dylib
2. put the lib here: /Users/<username>/Library/Python/<python_version>/lib/python/site-packages/py_mini_racer；You can find the specific download path for third-party Python packages on your own machine.

**Comment by albertandking** [comment]
> @vikasgola I have updated PyBroker to move the AKShare DataSource to a separate module. This should now no longer be an issue unless you explicitly import AKShare.

This is a good temporary solution to the problem.

**Comment by robustness-data** [comment]
Thank you all
