### ISSUE TITLE
How to use Model.pretrained?

### ISSUE THREAD

**Issue by isomorphicor** [edtechre/pybroker#46]
hi edtechre! i want to use one model for all my symbols,but i want still use the walkforward=3 or more , How to use pretrained model with walkforward windows larger than 1, can i use the fn load different models when walkforward to next windows?
ps: do you have the plan to support one model for all symbols?

**Comment by edtechre** [comment]
Hi @isomorphicor,

> How to use pretrained model with walkforward windows larger than 1, can i use the fn load different models when walkforward to next windows?

In order to support this, I can add the start and end times of each training window as arguments passed to your model loading function. Then you can check the arguments and load the appropriate model for each window.

> ps: do you have the plan to support one model for all symbols?

I can add support for global models, yes. However, I am interested to hear about your use case; do you plan to have a feature that is used to distinguish each ticker? For example, a one-hot encoding of the symbol of the bar (e.g. 0 for ticker A, 1 for ticker B, etc)?

**Comment by edtechre** [comment]
> In order to support this, I can add the start and end times of each training window as arguments passed to your model loading function. Then you can check the arguments and load the appropriate model for each window.

The change has been committed to the [dev branch](https://github.com/edtechre/pybroker/tree/dev) and will make it in the next v1.1.28 release.

**Comment by isomorphicor** [comment]
> I can add support for global models, yes. However, I am interested to hear about your use case; do you plan to have a feature that is used to distinguish each ticker? For example, a one-hot encoding of the symbol of the bar (e.g. 0 for ticker A, 1 for ticker B, etc)?

much thank you for support this in nxt version, and my case is: i only want to trainning one model for all tickers once per windows and all tickers have the same feature fields, their features  varying along time and ticker , i dont need to distinguish different ticker when infer just input different ticker's features . And indeed if i only tain along time dimension，i dont have enough samples. i want to combine CTA and Multi-factor strage togethor.

And i found a tmp ugly way to deal my case:  I modified the model.ModelsMixin.tain_models function, i change `model_result = source(sym, sym_train_data, sym_test_data)`  into `model_result = source(sym, train_data, test_data)`, and i add indicators to total train data and test data. then  i add my train_slr function with a global trained_models dict with begin_time+end_time id as keys, every time this user function be callback it will check if the model has been trained, if trained just fetch from the global dict. i also add `slice_by_symbol` function to my user train_slr function to deal with the case when i really want to distinct models along tickers.

**Comment by edtechre** [comment]
Added window start and end dates as arguments in [v1.1.28](https://github.com/edtechre/pybroker/releases/tag/v1.1.28)
