### ISSUE TITLE
Support for Trading Pairs

### ISSUE THREAD

**Issue by DominiqueGarmier** [edtechre/pybroker#47]
I just came across this project recently. I really like what saw so far!

I am wondering if you currently (... / are planing to) support trading individual pairs? As in multiple currencies (forex / crypto). From what I saw you only model positions with an opening and closing trade.

**Comment by edtechre** [comment]
Thank you @DominiqueGarmier,

Can you give more detail as to what you would like to see? Right now you can trade long and short positions in multiple instruments.

**Comment by DominiqueGarmier** [comment]
As an example on forex you could trade with three currencies A, B and C. Then you could buy B using A buy C using B and buy A using C. Guessing by your answer, I assume this can't be done.

**Comment by edtechre** [comment]
Thank you for the insight. No, this is not possible right now, but it is something I can consider adding in a future release.
