### ISSUE TITLE
How to train an uniform model for all symbols

### ISSUE THREAD

**Issue by ohfighting** [edtechre/pybroker#50]
Hi, edtechre
I was deeply attracted by pyb recently.
I want to train and backtest model using "Walkforward", but the framework of pyb  is based on one symbol one model.
Mining global rule is a native need for ML, e.g. technology stocks(goog, msft) may have same latent law.
So, In pybroker.model(...,fn(symbol, train_data, test_data),...), "symbol" may can be a group of symbols, as well as train_data and test_data?

**Comment by edtechre** [comment]
Hi @ohfighting,

Global models are not yet supported. This will be something I add eventually.

You can use a pretrained model to do this however. https://github.com/edtechre/pybroker/issues/46 has more information.
