### ISSUE TITLE
Failed in nopython mode pipeline (step: analyzing bytecode) op_MAKE_FUNCTION with annotations is not implemented

### ISSUE THREAD

**Issue by jingmouren** [edtechre/pybroker#56]
你好，
https://pypi.org/project/lib-pybroker/ 页面的例子
换用pandas的dataframe作源
strategy = Strategy(df, start_date='1/1/2022', end_date='7/1/2022')
   strategy.add_execution(
      exec_fn, ['000001', '600000'], indicators=highest('high_10d', 'close', period=10))
   # Run the backtest after 20 days have passed.
   result = strategy.backtest(warmup=20)

报标题错误。这是什么问题，如何解决？

docs里的notebooks 2. backtesting a strategy.ipynb 同样换df源正常执行

**Comment by edtechre** [comment]
Are you using Numba?

**Comment by jingmouren** [comment]
> Are you using Numba?

After I update numba, the example runs with that error disappear
