### ISSUE TITLE
Dealing with survivorship bias

### ISSUE THREAD

**Issue by snexus** [edtechre/pybroker#6]
Hi,

The project is very promising, thanks for that.

I couldn't find in the documentation how PyBroker deals with tickers that start missing data at a specific date, due to de-listing or bankruptcy.

For example, if I am using a custom DataSource based on pd.DataFrame, and backtesting from 2000-01 to 2020-01, rebalancing **every year.** Say if a given company goes bankrupt in the middle of 2015, what will happen when I try to sell it at the beginning of 2016, when rebalancing?

I understand this logic can be built on the algorithm side, but was wondering if PyBroker provides any built-in mechanisms. The simplest example - sell at the last provided price (which is mid-2015).
This leads to a more general question of how PyBroker deals with edge cases and if there are any safe-guards for custom data sources.

Thank you,
Denis

**Comment by edtechre** [comment]
Thank you for your question, snexus.

In PyBroker, the execution function is called separately for each symbol, and only when there are bars of data available. If there is no data available on a date, the execution function will not run for that missing bar.

Regarding your scenario, if you had bought a symbol in 2015, and there is no data available for that symbol in 2016, and you did not sell the symbol before it was delisted, then the position will still be held in your portfolio at the close price of the last available bar of data.

It would be difficult to determine what action to take when data ends, as PyBroker does not assume that the timestamps of bars for multiple symbols need to all be the same. It is not be clear when to raise an error condition after a certain amount of time elapses between bars of different symbols. But I am open to suggestions on how to handle this situation differently.

**Comment by snexus** [comment]
An ability to liquidate any held position would be great!

**Comment by edtechre** [comment]
Great, I will work on adding this now, and update this ticket once committed.

**Comment by edtechre** [comment]
Added [exit_on_last_bar](https://www.pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.exit_on_last_bar) option with https://github.com/edtechre/pybroker/commit/8f89571d8e062f58bb1e7ec2c3a1045758d15193

This will be in release v1.0.21

**Comment by snexus** [comment]
Thanks for that!

**Comment by edtechre** [comment]
Added in [v1.0.21](https://github.com/edtechre/pybroker/releases/tag/v1.0.21)
