### ISSUE TITLE
If the unique_syms should be uncached_syms at Line 232 of the data.py files?

### ISSUE THREAD

**Issue by isomorphicor** [edtechre/pybroker#64]
Hi edteche! I have a question as the issue title. hope for solve  it.

**Comment by isomorphicor** [comment]
![image](https://github.com/edtechre/pybroker/assets/12960324/04cfa722-b032-4e66-8f12-f5763b298a19)

**Comment by edtechre** [comment]
Yes, you are right. Thanks for catching!

Fixed in https://github.com/edtechre/pybroker/commit/e23b37b18cd556f2ec266899795aed26a9332194
