### ISSUE TITLE
Unclear which timezone between_time uses

### ISSUE THREAD

**Issue by Pirat83** [edtechre/pybroker#69]
Hi @edtechre, 

I have currently some issues with timezones. Especially *between_time* has unexpected behavior. So normally I integrate all my software systems in UTC timezone, since it is everywhere the same and there are no issues with daylight saving time and so on. 

When integrating trading systems with other systems it can be also an option to use the `US /Eastern` timezone. So I have taken a look at pybroker. 

Here is what happens (in my opinion): 
I can assrue that `start_date` and `end_date` are set up to use the `US/Eastern` timezone when I create them. 

![image](https://github.com/edtechre/pybroker/assets/16208524/b9801762-4d5c-4ab4-8f6b-a4a76223cbba)

* When creating Alpacas `StockBarsRequest` https://github.com/edtechre/pybroker/blob/master/src/pybroker/data.py#L357 both dates are converted to UTC which is fine 
![image](https://github.com/edtechre/pybroker/assets/16208524/19dbaf68-19cf-4af1-b4de-f8fe5960bf00)
* After the data is fetched from Alpaca the `DataFrame` is in UTC which is fine: 
![image](https://github.com/edtechre/pybroker/assets/16208524/d0b81ca6-0c0f-4228-8d27-e74c92e73ba3)
* https://github.com/edtechre/pybroker/blob/master/src/pybroker/data.py#L386 converts the `DataFrame` to US/Estern time which is not ideal for me but it works good enough. 
![image](https://github.com/edtechre/pybroker/assets/16208524/1241fce1-9bc6-45af-a730-9ef0c6836fbb)
* Then the data is fiterded: https://github.com/edtechre/pybroker/blob/master/src/pybroker/strategy.py#L1179

* After executing: https://github.com/edtechre/pybroker/blob/master/src/pybroker/strategy.py#L1346 the timezone is None and the `between_time` filtering is applied so I wanted to filter it by (9:30,16:00) `US/Estern`. 
![image](https://github.com/edtechre/pybroker/assets/16208524/e7ab4622-e945-4984-9e2c-5509ddefe1ef)

* But since the `date` column in the `DataFrame` does not have any timezone any more my `DataFrame` is broken after this method: 
![image](https://github.com/edtechre/pybroker/assets/16208524/7bdbac9c-81fa-4205-8fb8-7b0d61b70704)

So I will try to filter it with time in UTC timezone or `None` (which is supprisingly my local timezone)

I would strongly encourage using `time` with `timezone` instate of `string` tuples in `between_time`.  Maybe this thing can be done easier if `between_time` is a `tuple` of `time` objects?

**Comment by edtechre** [comment]
Hi @Pirat83,

Thank you for pointing this out. Yes, I can add an option that allows between_time to be a tuple of time objects so that timezone information is preserved.

**Comment by edtechre** [comment]
Hi @Pirat83,

Sorry for the delay. I am looking at this now.

I am not able to reproduce the issue you are having. Could you provide sample code here?  Also, which OS and version of Pandas are you using? I noticed that timezone conversion seems to work differently on Windows in Pandas.

FWIW, the between_time parameter ends up using Panda's [between_time](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.between_time.html) method to filter dates.

**Comment by Pirat83** [comment]
Hi @edtechre, I am using Linux.

**Comment by edtechre** [comment]
Thank you @Pirat83. That is the same as my setup. Can you provide me with sample code?

**Comment by Pirat83** [comment]
Hi @edtechre, Yes of course.

**Comment by edtechre** [comment]
Hi @Pirat83,

Let me know if this is still an issue.

**Comment by Pirat83** [comment]
Oh sorry. I will provide the code this week or close the ticket.

**Comment by Pirat83** [comment]
Hi @edtechre - I have added some example code to https://github.com/Pirat83/pybroker-experiments/tree/issue-69-and-51

**Comment by Pirat83** [comment]
So one of the main challenges is that pybroker dropps the timezone and then continues working with ´datetime´ without timezones. 

'datetime's are still in the US/Eastern timezone even if the timezone is not present any more. If someone want's to filter for some candles then ´datetime´s need to be used without timezone but they must match the US/Eastern timezone.

**Comment by edtechre** [comment]
Hi @Pirat83,

Sorry for the late response. The timezone information is dropped in order to support to filter backtesting data by the start/end date arguments, because those are datetime objects without timezone information. This happens independently of using ``between_time``.

Note, filtering with ``between_time`` uses Pandas' [between_time](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.between_time.html) filtering.

I would suggest performing any filtering on your DataFrame before executing your backtest on it. This can be done by querying your DataSource for the DataFrame, and then passing the modified DataFrame as your DataSource to the Strategy. [See this notebook for an example](https://www.pybroker.com/en/latest/notebooks/7.%20Creating%20a%20Custom%20Data%20Source.html#Using-a-Pandas-DataFrame).

If that is not enough, then I suggest assuming that you are dealing with times that have been normalized to US/Eastern, as you mentioned.
