### ISSUE TITLE
profit_factor below confidence interval

### ISSUE THREAD

**Issue by saddy001** [edtechre/pybroker#73]
When using `result = strategy.backtest(calc_bootstrap=True, train_size=0.5)` I often see the `result.metrics.profit_factor` being _lower_ than `result.bootstrap.profit_factor.low_2p5`. I see it more often than one would expect from a 2.5% chance.

I have two questions:
1. Can you confirm this (without a minimal reproducing example)?
2. Is boostrapping in combination with the train_size parameter even supported?

**Comment by edtechre** [comment]
low_2p5 does not represent a 2.5% chance. It represents a 97.5% confidence interval.

For #2, bootstrapping samples from the test splits. The train_size param specifies how large the train/test splits are.
