### ISSUE TITLE
How to specify the closing price as the opening price of the next bar in Strategy.backtest()?

### ISSUE THREAD

**Issue by vensentzhou** [edtechre/pybroker#74]

**Comment by edtechre** [comment]
You can't, but you can set the fill price to PriceType.CLOSE. See [buy_fill_price](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecResult.buy_fill_price) and [sell_fill_price](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecResult.sell_fill_price).

You can also retrieve the previous day's open price using ``ctx.open[-2]``.
