### ISSUE TITLE
pip install lib-pybroker fail

### ISSUE THREAD

**Issue by young-tim** [edtechre/pybroker#78]
I am using macOS 10.14 system, and I encountered a failure while installing lib-pybroker in a Conda virtual environment. I have successfully installed all the packages listed in the requirements.txt file of the source code.

The specific error message is as follows:

(quantitative) MacBook-Pro:pybroker Xxx$ pip install pybroker
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement pybroker (from versions: none)
ERROR: No matching distribution found for pybroker
(quantitative) MacBook-Pro:pybroker Xxx$ pip install lib-pybroker -i https://pypi.org/simple
Collecting lib-pybroker
  Downloading lib-pybroker-1.1.29.tar.gz (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.3/99.3 kB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: akshare<2,>=1.10.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (1.11.79)
Requirement already satisfied: alpaca-py<1,>=0.7.2 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (0.13.3)
Requirement already satisfied: diskcache<6,>=5.4.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (5.6.3)
Requirement already satisfied: joblib<2,>=1.2.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (1.3.2)
Requirement already satisfied: numba<1,>=0.56.3 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (0.58.1)
Requirement already satisfied: numpy<2,>=1.23.4 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (1.26.2)
Collecting pandas<2,>=1.5.1 (from lib-pybroker)
  Downloading pandas-1.5.3-cp310-cp310-macosx_10_9_x86_64.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 8.2 MB/s eta 0:00:00
Requirement already satisfied: progressbar2<5,>=4.1.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from lib-pybroker) (4.2.0)
Collecting yfinance<1,>=0.1.84 (from lib-pybroker)
  Downloading yfinance-0.2.32-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: beautifulsoup4>=4.9.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (4.12.2)
Requirement already satisfied: lxml>=4.2.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (4.7.0)
Requirement already satisfied: requests>=2.22.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (2.31.0)
Requirement already satisfied: pypinyin>=0.35.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (0.49.0)
Requirement already satisfied: html5lib>=1.0.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (1.1)
Requirement already satisfied: xlrd>=1.2.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (2.0.1)
Requirement already satisfied: urllib3>=1.25.8 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (2.1.0)
Requirement already satisfied: tqdm>=4.43.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (4.66.1)
Requirement already satisfied: openpyxl>=3.0.3 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (3.1.2)
Requirement already satisfied: jsonpath>=0.82 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (0.82.2)
Requirement already satisfied: tabulate>=0.8.6 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (0.9.0)
Requirement already satisfied: decorator>=4.4.2 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (5.1.1)
Requirement already satisfied: py-mini-racer>=0.6.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (0.6.0)
Requirement already satisfied: akracer>=0.0.11 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from akshare<2,>=1.10.1->lib-pybroker) (0.0.13)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from alpaca-py<1,>=0.7.2->lib-pybroker) (1.0.7)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from alpaca-py<1,>=0.7.2->lib-pybroker) (2.5.2)
Requirement already satisfied: sseclient-py<2.0.0,>=1.7.2 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from alpaca-py<1,>=0.7.2->lib-pybroker) (1.8.0)
Requirement already satisfied: websockets<12.0.0,>=11.0.3 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from alpaca-py<1,>=0.7.2->lib-pybroker) (11.0.3)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from numba<1,>=0.56.3->lib-pybroker) (0.41.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from pandas<2,>=1.5.1->lib-pybroker) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from pandas<2,>=1.5.1->lib-pybroker) (2023.3.post1)
Requirement already satisfied: python-utils>=3.0.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from progressbar2<5,>=4.1.1->lib-pybroker) (3.8.1)
Requirement already satisfied: multitasking>=0.0.7 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from yfinance<1,>=0.1.84->lib-pybroker) (0.0.11)
Collecting lxml>=4.2.1 (from akshare<2,>=1.10.1->lib-pybroker)
  Downloading lxml-4.9.3.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting appdirs>=1.4.4 (from yfinance<1,>=0.1.84->lib-pybroker)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting frozendict>=2.3.4 (from yfinance<1,>=0.1.84->lib-pybroker)
  Downloading frozendict-2.3.9-cp310-cp310-macosx_10_9_x86_64.whl.metadata (20 kB)
Collecting peewee>=3.16.2 (from yfinance<1,>=0.1.84->lib-pybroker)
  Downloading peewee-3.17.0.tar.gz (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 12.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: soupsieve>1.2 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from beautifulsoup4>=4.9.1->akshare<2,>=1.10.1->lib-pybroker) (2.5)
Requirement already satisfied: six>=1.9 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from html5lib>=1.0.1->akshare<2,>=1.10.1->lib-pybroker) (1.16.0)
Requirement already satisfied: webencodings in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from html5lib>=1.0.1->akshare<2,>=1.10.1->lib-pybroker) (0.5.1)
Requirement already satisfied: et-xmlfile in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from openpyxl>=3.0.3->akshare<2,>=1.10.1->lib-pybroker) (1.1.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py<1,>=0.7.2->lib-pybroker) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.5 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py<1,>=0.7.2->lib-pybroker) (2.14.5)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py<1,>=0.7.2->lib-pybroker) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from requests>=2.22.0->akshare<2,>=1.10.1->lib-pybroker) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from requests>=2.22.0->akshare<2,>=1.10.1->lib-pybroker) (3.5)
Requirement already satisfied: certifi>=2017.4.17 in /Users/Xxx/.conda/envs/quantitative/lib/python3.10/site-packages (from requests>=2.22.0->akshare<2,>=1.10.1->lib-pybroker) (2023.11.17)
Downloading yfinance-0.2.32-py2.py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 2.3 MB/s eta 0:00:00
Downloading frozendict-2.3.9-cp310-cp310-macosx_10_9_x86_64.whl (36 kB)
Building wheels for collected packages: lib-pybroker, lxml, peewee
  Building wheel for lib-pybroker (pyproject.toml) ... done
  Created wheel for lib-pybroker: filename=lib_pybroker-1.1.29-py3-none-any.whl size=71825 sha256=b9db78455d0672c6bf18171f4ff00ebcc8df11a5ab7655df3cfb9a40686e1888
  Stored in directory: /Users/Xxx/Library/Caches/pip/wheels/e1/bc/eb/f36148fc0144901bd21f9a6572b6fb72769ec8e0541d372c1e
  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      Building lxml version 4.9.3.
      /private/var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn/T/pip-install-59lluing/lxml_e9c9fa4358b64bbc91e6a3f26a68f09a/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building without Cython.
      Building against libxml2 2.9.2 and libxslt 1.1.28
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-310
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/sax.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/builder.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/html
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/objectify.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/etree.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/public-api.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xmlid.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/cleanup.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xslt.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xpath.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/debug.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/serializer.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/classlookup.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/saxparser.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/objectpath.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/relaxng.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xinclude.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/iterparse.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/parser.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/dtd.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/extensions.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/schematron.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/docloader.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/xsltext.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/proxy.pxi -> build/lib.macosx-10.9-x86_64-cpython-310/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/rng
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.9-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-10.9-x86_64-cpython-310
      creating build/temp.macosx-10.9-x86_64-cpython-310/src
      creating build/temp.macosx-10.9-x86_64-cpython-310/src/lxml
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/Xxx/.conda/envs/quantitative/include -fPIC -O2 -isystem /Users/Xxx/.conda/envs/quantitative/include -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/Users/Xxx/.conda/envs/quantitative/include/python3.10 -c src/lxml/etree.c -o build/temp.macosx-10.9-x86_64-cpython-310/src/lxml/etree.o -w -flat_namespace
      In file included from src/lxml/etree.c:864:
      src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
      #include "libxml/xmlversion.h"
               ^
      1 error generated.
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/t3
      creating var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn
      creating var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn/T
      cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn/T/xmlXPathInitainbuq9j.c -o var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn/T/xmlXPathInitainbuq9j.o
      /var/folders/t3/58ns5ktj705bstp2bzfbpkqr0000gn/T/xmlXPathInitainbuq9j.c:1:10: fatal error: 'libxml/xpath.h' file not found
      #include "libxml/xpath.h"
               ^
      1 error generated.
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.0-cp310-cp310-macosx_10_9_x86_64.whl size=255501 sha256=0a1f570d6ec6f16531907c3e21175faf301076fdb05f470460daf76c4584b7a8
  Stored in directory: /Users/Xxx/Library/Caches/pip/wheels/c7/70/ad/212867e96e7004265a69c4aa5dcff00a95f547a67ba26e7e76
Successfully built lib-pybroker peewee
Failed to build lxml
ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects

**Comment by young-tim** [comment]
The issue has been resolved by installing the corresponding versions of the packages step by step.

**Comment by arisliang** [comment]
I was using uv pip, turn out just using pip without uv, works.

**Comment by arisliang** [comment]
lxml 5.3.0 can be easily installed using pip, can we upgrade to use this version?

**Comment by arisliang** [comment]
After switch to ubuntu (wsl), installation is successful

**Comment by playgithub** [comment]
https://github.com/edtechre/pybroker/blob/master/requirements.txt

> akshare>=1.10.1
> alpaca-py>=0.7.2
> diskcache>=5.4.0
> flake8>=5.0.4
> flake8-bugbear>=22.10.25
> joblib>=1.2.0
> jupyter>=1.0.0
> matplotlib>=3.9.1
> mypy>=0.982
> nbsphinx>=0.8.11
> numba>=0.60.0
> numpy>=1.26.4,<2
> pandas>=2.2.0
> progressbar2>=4.1.1
> pytest>=7.2.0
> pytest-cov>=4.0.0
> pytest-instafail>=0.4.2
> pytest-randomly>=3.12.0
> pytest-xdist>=3.0.2
> ruff>=0.3.4
> scikit-learn>=1.5.1
> Sphinx>=5.3.0
> sphinx_rtd_theme>=2.0.0
> sphinx-intl>=2.1.0
> yahooquery>=2.3.7
> yfinance>=0.1.84

when install the requirements one by one, every one is ok except `yahooquery`, which is relevant to the problem.

**Comment by gazhao80** [comment]
same error?
Building wheels for collected packages: lxml                                                                                                                          
  Building wheel for lxml (pyproject.toml) ... error                                                                                                                  
  error: subprocess-exited-with-error                                                                                                                                 
                                                                                                                                                                      
  × Building wheel for lxml (pyproject.toml) did not run successfully.                                                                                                
  │ exit code: 1                                                                                                                                                      
  ╰─> [206 lines of output]                                                                                                                                           
      <string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html                             
      /tmp/pip-build-env-pypx_m0o/overlay/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.      
      !!                                                                                                                                                              
                                                                                                                                                                      
              ********************************************************************************                                                                        
              Please consider removing the following classifiers in favor of a SPDX license expression:                                                               
                                                                                                                                                                      
              License :: OSI Approved :: BSD License                                                                                                                  
                                                                                                                                                                      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.                                                          
              ********************************************************************************                                                                        
                                                                                                                                                                      
      !!                                                                                                                                                              
        self._finalize_license_expression()                                                                                                                           
      Building lxml version 4.9.4.                                                                                                                                    
      Building without Cython.                                                                                                                                        
      Building against libxml2 2.9.10 and libxslt 1.1.34

**Comment by playgithub** [comment]
I've solved it by using the venv tool `uv` which can use a older version of python.
