### ISSUE TITLE
Minute "bar" support

### ISSUE THREAD

**Issue by spinus** [edtechre/pybroker#8]
I went across the docs and I only see that bar means day. 
In a lot of cases that's not enough.
1. There is case when algorithm is running on more granular data.
2. There is case when bar is forming (before its bar window is closed) on live trading. Would be great that that backtesting algorithm support this scenario as it may give very different results when switching to live.

**Comment by edtechre** [comment]
Thank you for your feedback, @spinus!

Regarding your first point, bars in PyBroker do not necessarily represent days. Instead, they represent the granularity of the data used for backtesting. For example, if you are using per-minute data, then bars will be per-minute as well.

As for your second point, I'm not quite sure how that would work. You can increase the granularity of your data to whatever you like, but the framework assumes that bars are discrete time steps that have already completed.

**Comment by spinus** [comment]
@edtechre thank you for very fast response.
1. That makes sense. Just documentation was misleading in few places as it refers to bars as days and I didn't find any general statement about that. Maybe worth clarifying. 
2. Right, but often you cannot get second or minute level data, so your backtesting can be misleading when later algorithm is switched to live trading and won't be tested on sensitive "bar building" events which can trigger events that on daily level data that wouldn't be trigger. One idea for that, would be adding generation of sub-level bars.
