### ISSUE TITLE
Support Pandas 2

### ISSUE THREAD

**Issue by edtechre** [edtechre/pybroker#83]
+ @albertandking

**Comment by albertandking** [comment]
Hello Ed, I think we can skip compatibility with Pandas version 1.0 for this upgrade. 
1. This allows us to fully utilize the features of pandas 2.2
2. It helps keep the code concise, which is beneficial for maintenance and upgrades. 
3. Since Pybroker is highly dependent on Pandas, it would be best to maintain only the main version.

**Comment by edtechre** [comment]
Hi @albertandking,

Thank you for your input. I think we should still maintain compatibility with older versions of Pandas since not all users have migrated to Pandas 2.0.  And PyBroker's dependencies like YFinance and Alpaca still support Pandas 1.

Note, PyBroker avoids using Pandas as much as possible due to its general opaque and variable (bad) performance. Pandas is used for querying from DataSources, and then slicing and querying column values. But computation is largely done outside of Pandas using NumPy arrays, which greatly helps to optimize PyBroker's performance.

Generally, I want to keep PyBroker from being reliant on Pandas as much as possible, and only use it for querying data and storing test results.

**Comment by edtechre** [comment]
I checked in changes make PyBroker compatible with Pandas 2.0. 

However, I noticed that YFinance does not work correctly with Pandas 2.0.  

I am leaving Pandas compatibility as <2 for now until the dependencies catch up. However, anyone should now be able to update to Pandas 2.0 without any issues in the PyBroker code.

**Comment by none2003** [comment]
Is it possible to make pybroker to compatible with pandas 1 and 2 at the same time?

**Comment by edtechre** [comment]
Both Pandas 1.0 and 2.0 are now supported. Pandas 2.0 is now the default dependency.
