### ISSUE TITLE
Support custom fee structure

### ISSUE THREAD

**Issue by edtechre** [edtechre/pybroker#86]
Add support for custom fee calculations by introducing a FeeStructure ABC that can be set on a Strategy instance.

**Comment by edtechre** [comment]
@albertandking This can be used to support fees on a Chinese exchange.

**Comment by albertandking** [comment]
> @albertandking This can be used to support fees on a Chinese exchange.

yes，it's a good idea, I will try to make it

**Comment by edtechre** [comment]
I added support for setting ``StrategyConfig.fee_mode`` to a Callable that handles the custom fee calculation. See [fee_mode](https://www.pybroker.com/en/dev/reference/pybroker.config.html#pybroker.config.StrategyConfig.fee_mode).

Committed to dev branch and targeted for v1.1.31 release.
