### ISSUE TITLE
question about ctx.dt and indicator value

### ISSUE THREAD

**Issue by none2003** [edtechre/pybroker#88]
Hi @edtechre,

Does ctx.dt represents the date of current bar? If so, shouldn't ctx.indicator('xxx')[-1] give previous bar's indicator value?

I was running "10. Rotational Trading.ipynb" and did some changes to "rotate" function:

```
def rotate(ctx: ExecContext):
    x = ctx.indicator('roc_20')[-1] 
    print(f'ctx.dt={ctx.dt}, roc_20={x}') # <---added to print date and roc_20 value
    if ctx.long_pos():
        if ctx.symbol not in pyb.param('top_symbols'):
            ctx.sell_all_shares()
    else:
        target_size = pyb.param('target_size')
        ctx.buy_shares = ctx.calc_target_shares(target_size)
        ctx.score = ctx.indicator('roc_20')[-1]
```

I also did roc_20 calculation by using code:
```
...
df = pybroker_ds.query(symbols=symbols, start_date=start_date, end_date=end_date)
...
```

They both gives same output:

symbol|date|roc_20
-- | -- | --
AAPL | 2022/6/30 | -8.062675645
AMD | 2022/6/30 | -24.45168909
AMZN | 2022/6/30 | -12.71654389
GOOG | 2022/6/30 | -4.174372408
INTC | 2022/6/30 | -15.189301
META | 2022/6/30 | -14.51971983
MSFT | 2022/6/30 | -5.722790576
NFLX | 2022/6/30 | -9.351515319
NVDA | 2022/6/30 | -17.25436743
TSLA | 2022/6/30 | -9.042775743
AAPL | 2022/6/29 | -6.456598258
AMD | 2022/6/29 | -23.43412783
AMZN | 2022/6/29 | -9.391524552
GOOG | 2022/6/29 | -1.56306281
INTC | 2022/6/29 | -16.05132271
META | 2022/6/29 | -15.33773861
MSFT | 2022/6/29 | -4.270418053
NFLX | 2022/6/29 | -9.663696108
NVDA | 2022/6/29 | -16.76306922
TSLA | 2022/6/29 | -9.599604985

That makes me wonder, why the AAPL's roc_20[-1] on 'ctx.dt==2022/6/30' is "-8.062675645" rather than previous bar's "-6.456598258"

**Comment by edtechre** [comment]
Hi @none2003, the "current bar" is the last completed bar, so this is correct.

**Comment by none2003** [comment]
Hi,

So, what does the ctx.dt mean? Is there any variable that can get the time of the current bar?

**Comment by edtechre** [comment]
As I said, the "current bar" is the last bar that was completed. The "current" date is the date that accompanies that bar in your data source.
