### ISSUE TITLE
有考虑接入okx biance的数据么

### ISSUE THREAD

**Issue by shashlik007** [edtechre/pybroker#94]
如题

**Comment by edtechre** [comment]
Hi @shashlik007. There is no Binance support right now, but you are free to download the data yourself and use it with PyBroker. [See here](https://www.pybroker.com/en/latest/notebooks/7.%20Creating%20a%20Custom%20Data%20Source.html#Using-a-Pandas-DataFrame).

**Comment by River-Shi** [comment]
> 如题

可以用binance_data_dwonload 下载然后储存到本地数据库，我用的是duckdb，然后再自定义一个datasource即可
