### ISSUE TITLE
caching data bug in month or week frequence

### ISSUE THREAD

**Issue by frankygtd** [edtechre/pybroker#96]
I just read the code in class DataSource.
it will concatenate cached data and uncached data by "df = pd.concat((cached_df, df))".
then there will be a bug when frequency is month or week.
here are some example data.
![image](https://github.com/edtechre/pybroker/assets/45612096/6b073e41-9c77-4d55-a71b-deecc13d39bf)
weekly data before 2024-01-05 is cached.
![image](https://github.com/edtechre/pybroker/assets/45612096/7f016326-7b69-4234-aa75-53b20b9c40ff)
monthly data before 2024-01-05 is cached.

three cached points: 2024-01-05, 2024-01-16, 2024-01-19

raw data is correct.
![image](https://github.com/edtechre/pybroker/assets/45612096/a126845a-1154-4d8f-9b51-1904c958b2df)

please help to check it, thanks

**Comment by edtechre** [comment]
Thank you @frankygtd. Can you provide sample code to reproduce this? Monthly caching is no longer supported as of v1.1.30.

**Comment by frankygtd** [comment]
if so, I will close caching option for monthly data. Thanks
